# NumPy


* NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
* NumPy is also incredibly fast, as it has bindings to C libraries.


* Numpy arrays essentially come in two flavors: vectors and matrices.
* Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


1-d =>     ( )

2-d =>   ( ( ) )

3-d => ( ( ( ) ) )

## NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [6]:
arr=np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# arange() function in numpy like as range function in arrays.
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
# this command is use to make array of zeros.
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# linspace command give random point between the two values.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.linspace(0,199,10)

array([  0.        ,  22.11111111,  44.22222222,  66.33333333,
        88.44444444, 110.55555556, 132.66666667, 154.77777778,
       176.88888889, 199.        ])

In [30]:
# It's call identity matrix. it's give same no. rows and columns.
# It must be square of any value
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# This command give random value
np.random.rand(5,2)

array([[0.79826243, 0.53664507],
       [0.28096628, 0.51627747],
       [0.63530188, 0.67269774],
       [0.63611597, 0.55371524],
       [0.43137208, 0.08223435]])

In [36]:
np.random.randn(4,4)

array([[ 0.09484128, -1.6710976 ,  1.34514496, -3.29710726],
       [-0.58331116,  0.36354367, -0.23259911,  0.21287343],
       [-1.10858151,  0.14399298, -1.34493342,  0.10675621],
       [ 0.70220619,  0.77927897,  0.6309316 , -1.34085662]])

In [38]:
# This command give random interger value between two points.
np.random.randint(1,100,10)

array([32, 96, 30, 91, 85, 53, 28, 88, 62, 66])

In [47]:
arr = np.arange(0,50,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [42]:
arrr=np.random.randint(0,50,25)
arrr

array([29, 29, 41, 49,  8, 44, 45, 34, 46, 33,  5, 12, 45,  6, 21, 10, 42,
       22, 49, 20, 31,  4, 31, 29, 48])

In [48]:
# this command change the diamentions of array
arr.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [49]:
arrr

array([29, 29, 41, 49,  8, 44, 45, 34, 46, 33,  5, 12, 45,  6, 21, 10, 42,
       22, 49, 20, 31,  4, 31, 29, 48])

In [51]:
# min() command use to take min value from array as well as max
arrr.min()
arrr.max()

49

In [54]:
# argmax() command show the index location of max value and min value as well
print(arrr.argmax())
print(arrr.argmin())

3
21


In [56]:
# shape command use to check shape of the array
arr.shape

(25,)

In [57]:
arr.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [58]:
arr.dtype

dtype('int64')

In [59]:
from numpy.random import randint

In [61]:
randint(2,10,5)

array([8, 3, 7, 3, 3])

In [3]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the XOR function
def xor_function(x1, x2):
    return x1 ^ x2

# Define the neural network class
class XORNeuralNetwork:
    def __init__(self):
        # Initialize the weights with random values
        self.weights1 = np.random.rand(2, 2)
        self.weights2 = np.random.rand(2, 1)
        self.bias1 = np.random.rand(1, 2)
        self.bias2 = np.random.rand(1, 1)

    def feed_forward(self, inputs):
        # Calculate the values of the hidden layer
        self.hidden_layer = sigmoid(np.dot(inputs, self.weights1) + self.bias1)

        # Calculate the output layer
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights2) + self.bias2)

        return self.output

    def backpropagation(self, inputs, targets, learning_rate):
        # Perform feed-forward
        self.feed_forward(inputs)

        # Calculate the error in the output layer
        output_error = targets - self.output
        output_delta = output_error * sigmoid_derivative(self.output)

        # Calculate the error in the hidden layer
        hidden_error = np.dot(output_delta, self.weights2.T)
        hidden_delta = hidden_error * sigmoid_derivative(self.hidden_layer)

        # Update the weights and biases
        self.weights2 += np.dot(self.hidden_layer.T, output_delta) * learning_rate
        self.bias2 += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
        self.weights1 += np.dot(inputs.T, hidden_delta) * learning_rate
        self.bias1 += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

    def train(self, inputs, targets, epochs, learning_rate):
        for epoch in range(epochs):
            self.backpropagation(inputs, targets, learning_rate)

    def predict(self, inputs):
        return np.round(self.feed_forward(inputs))

# Define the XOR inputs and targets
xor_inputs = np.array([[0, 0],
                       [0, 1],
                       [1, 0],
                       [1, 1]])

xor_targets = np.array([[xor_function(0, 0)],
                        [xor_function(0, 1)],
                        [xor_function(1, 0)],
                        [xor_function(1, 1)]])

# Create a XOR neural network
xor_nn = XORNeuralNetwork()



In [ ]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
 return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
 return x * (1 - x)
# Define the XOR function dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])
# Set the random seed for reproducibility
np.random.seed(42)
# Initialize the weights and biases with random values
weights1 = np.random.rand(2, 2)
bias1 = np.random.rand(1, 2)
weights2 = np.random.rand(2, 1)
bias2 = np.random.rand(1, 1)
# Set the learning rate and number of iterations
learning_rate = 0.1
num_iterations = 10000
# Training loop
for iteration in range(num_iterations):
 # Forward propagation
 layer1_output = sigmoid(np.dot(X, weights1) + bias1)
 layer2_output = sigmoid(np.dot(layer1_output, weights2) + bias2)

 # Backpropagation
 layer2_error = y - layer2_output
 layer2_delta = layer2_error * sigmoid_derivative(layer2_output)
 layer1_error = np.dot(layer2_delta, weights2.T)
 layer1_delta = layer1_error * sigmoid_derivative(layer1_output)
 # Update weights and biases
 weights2 += np.dot(layer1_output.T, layer2_delta) * learning_rate
 bias2 += np.sum(layer2_delta, axis=0, keepdims=True) * learning_rate
 weights1 += np.dot(X.T, layer1_delta) * learning_rate
 bias1 += np.sum(layer1_delta, axis=0, keepdims=True) * learning_rate
# Test the trained network
test_output = sigmoid(np.dot(sigmoid(np.dot(X, weights1) + bias1), weights2) + bias2)
print("Predicted Output:")
print(test_output.round())